spring.application.name=publica

# ==============================
# MySQL — ajuste usuario e senha
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/biblioteca_publica?createDatabaseIfNotExist=true&serverTimezone=America/Fortaleza
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==============================
# Flyway
# ==============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
